"""Add reminder_sent to tasks

Revision ID: 16aa9b55cf07
Revises: 297a96e6681c
Create Date: 2026-09-18 14:13:40.832715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16aa9b55cf07'
down_revision = '297a96e6681c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
